### ISSUE TITLE
soft_assertions does not work correctly with has_

### ISSUE THREAD

**Issue by zaz600** [ActivisionGameScience/assertpy#64]
```
Python 3.5.2
assertpy (0.10)
```

soft_assertions does not work correctly with `has_` from dynamic assertions.

### Example 

```py
from assertpy import assert_that, soft_assertions

d = {'a': 1, 'b': 2}

with soft_assertions():
    assert_that(d).has_a(3)
    assert_that(d).has_b(4)
    assert_that(d).has_aa(1)
    assert_that(d).has_bb(2)
```
output:

```
Traceback (most recent call last):
  File "1.py", line 9, in <module>
    assert_that(d).has_aa(1)
  File "/usr/local/lib/python3.5/dist-packages/assertpy/assertpy.py", line 879, in __getattr__
    raise KeyError('val has no key <%s>' % attr_name)
KeyError: 'val has no key <aa>'
```
Expected:
```
...
AssertionError: soft assertion failures:
1. Expected <1> to be equal to <3>, but was not.
2. Expected <2> to be equal to <4>, but was not.
3. Expected <aa> to be equal to <1>, but val has no key <aa>.
4. Expected <bb> to be equal to <2>, but val has no key <bb>.
```

**Comment by saturnboy** [comment]
@zaz600 Per the docs:

```Also, note that only assertion failures are collected, errors such as TypeError
    or ValueError are raised immediately.

**Comment by saturnboy** [comment]
@zaz600 changed dynamic assertions to throw `AssertionError` but **only** in the case of missing key or attribute.  See 9958bce

Can you check if this works for you in your use case?

**Comment by zaz600** [comment]
Thank you!
This is what I need.

>> The goal is to fail fast and alert you (the test developer) that you have a bad test, not just a bad assertion. 

I make tests for REST API (JSON), where some attributes (dict keys) may be missing as a result of a server error
